### ISSUE TITLE
Ping command improvements

### ISSUE THREAD

**Issue by Seemone** [inhies/cjdcmd#11]
Normal ping command sends one packet each second (by default). cjdcmd ping command sends a new packet as soon as it receives a response. This is not effective for 2 reasons: it on broadband links it sends a lot of packets, much faster than a human can notice their latency and is more vulnerable to lost packets, not giving a meaningful picture of packet loss en route towards that target.

Proposed solution: send one packet each second, regardless of when its response comes in and print a summary a-la normal ping after ctrl-c is issued. Optional parameter to increase delay.

**Comment by inhies** [comment]
Great idea, this will get implemented soon. I also have more graceful error handling in the even of a packet error planned for the same time. Thank you.

**Comment by Seemone** [comment]
Also, it shouldn't quit if the target can't be reached anymore.

**Comment by inhies** [comment]
Agreed, that's part of the 'better error handling' :)
