### ISSUE TITLE
Check for a path to hypedns before attempting to resolve

### ISSUE THREAD

**Issue by inhies** [inhies/cjdcmd#12]
To prevent timeouts and other errors, dump the routing table and check for a path to the hypedns IP before we attempt to use it.

**Comment by waaghals** [comment]
Proposal:
First check the clearnetDNS if it is a known TLD.
Then use the clearnetDNS else HypeDNS if it is reachable.

**Comment by inhies** [comment]
That mightcould work. If hypedns is reachable, it will resolve known TLDs as well as hyperboria only ones. I figure it might save some time to try hypedns first.
