### ISSUE TITLE
Configuration / Settings File

### ISSUE THREAD

**Issue by inhies** [inhies/cjdcmd#24]
Cjdcmd has a lot of options that can be confusing. I would like to specify a default configuration file that it can use so that less data needs to be entered for each command. 

Items that would be in this file:
- Location of cjdroute.conf
- Admin port connection details
- Custom formatting options for future customized output formats for the various functions
- Probably some other stuff I'm forgetting

Possible locations for this file:
- ~/.cjdcmd
- ~/.cjdadmin (expand upon this file that some users already have from the python programs for cjdns)
- /etc/cjdcmd.conf 

I'm looking for input as to what other users would like to see. As cjdcmd gets more complicated the need for a configuration file gets worse and worse.

**Comment by waaghals** [comment]
Although i'm not a fan of ~/.cjdadmin it seem to be the prefered method for others.
I see no problem in adding stuff to this file as it won't break other scripts.

**Comment by inhies** [comment]
Implemented in v0.5.1

Uses ~/.cjdnsadmin with the standard fields, as well as one added field for default configuration file location. The command `cjdnsadmin` will automatically generate this file as long as you specified a cjdroute.conf to build it from with the --file flag.
