### ISSUE TITLE
cleanconfig command doesn't work?

### ISSUE THREAD

**Issue by danry25** [inhies/cjdcmd#26]
Hey, I'm trying to get cjdcmd to clean my config file of all the comments & non-JSON friendly stuff using cleanconfig, but I keep getting this:
user@laptop ~ $ cjdcmd cleanconfig -file=/home/user/cjdns/cjdroute.conf -outfile file=/home/user/cjdns/cjdroute2.conf
Loading configuration from: /home/user/cjdns/cjdroute.conf... Error loading config: invalid character '"' after object key:value pair

**Comment by inhies** [comment]
Clean config just strips out comments and re-formats the JSON with proper indenting. Unfortunately I have no means to debug invalid JSON beyond what it already spits out so your best bet is to run it through an external JSON validator to get some help. I use [this one](http://jsonformatter.curiousconcept.com)

**Comment by danry25** [comment]
Oh well
